[finishes 187511688]-implement-badges-status(CI/CD)-show-whether-pass…
atlp-rwanda/e-commerce-mavericcks-bn pull request #42
Opened 2024-04-29 11:46 UTC by hozayves

## Purpose

The Build Status Badge (CI/CD) serves as an indicator of the status of our continuous integration/continuous deployment (CI/CD) pipeline. It offers clarity to users and contributors regarding the current state of our build process, whether it has passed or failed.

## Changes Made

- The README.md file was updated.
- Modifications were implemented in the CI/CD pipeline file to enable sending coverage reports to coveralls.io.
- Adjustments were made in the test suite to include tests for functions created in the controller, ensuring coverage reports can be sent to Coveralls. These tests serve as samples and may be removed once tests for endpoints are implemented.

## Testing Instructions

Please refer to the README in the GitHub repository for details.

## Related Issues

None

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [ ] Code follows the project's coding standards
- [ ] Changes are covered by tests
- [ ] Documentation is updated (if applicable)
- [ ] All tests pass

2024-04-29 21:32 UTC, Munezero2000 approved these changes

2024-04-30 06:53 UTC, niyontwali requested changes

2024-04-30 06:53 UTC, niyontwali commented on README.md
> +[![Maintainability](https://api.codeclimate.com/v1/badges/44cd8dee96aeb01f2dd0/maintainability)](https://github.com/atlp-rwanda/e-commerce-mavericcks-bn.git)
Please remove this badge and we shall be good to go

2024-05-01 20:21 UTC, patrickhag approved these changes

2024-05-01 20:37 UTC, gracemugwanezak approved these changes

2024-05-01 21:10 UTC, niyontwali approved these changes

2024-05-06 08:30 UTC, merged