#187354235 test configuration
atlp-rwanda/e-commerce-mavericcks-bn pull request #5
Opened 2024-04-05 08:30 UTC by A-gent64

## Purpose

To codeclimate & test configuration

## Changes Made

Added a simple route test

## Testing Instructions

Run(npm test to see that the test is working)

## Related Issues

No issue

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- 

- [ ] Code follows the project's coding standards

- [ ] Changes are covered by tests
- [ ] Documentation is updated (if applicable)
- [ ] All tests pass

2024-04-05 08:59 UTC, Favor-star approved these changes
Look Good To Me

2024-04-05 09:18 UTC, amin-leon approved these changes
Great

2024-04-05 10:29 UTC, gracemugwanezak approved these changes

2024-04-05 13:37 UTC, Munezero2000 approved these changes

2024-04-08 23:32 UTC, hozayves requested changes
Hey there! Thanks for your contribution! Just a quick note: it's best practice not to push **node_modules**, **coverages**, and **dist** directories to the repository as they can be generated locally and tend to bloat the repository size. Let's keep our repository clean and focused. Thanks for understanding! @A-gent64 @hatfelicien

2024-04-09 09:53 UTC, closed without merging