[Finsishes #187354256] Marking product as available or unavailable
atlp-rwanda/e-commerce-mavericcks-bn pull request #61
Opened 2024-05-09 10:16 UTC by amin-leon

## Purpose

Products should be availed for buyers to purchase
As a seller I should be able to mark a product as available or unavailable manually in order to make it available for the buyers on not.
Reasons can be: expiry date, low on stock.

## Changes Made

- I ve added available attribute on Size model
- i ve created new migration to add available attribute
- Created two controllers: markProductAsUnavailable and markProductAsAvailable
- Documented two routes using swagger

## Testing Instructions

None

## Related Issues

None

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [x] Code follows the project's coding standards
- [x] Changes are covered by tests
- [x] Documentation is updated (if applicable)
- [x] All tests pass

2024-05-09 15:52 UTC, hozayves approved these changes

2024-05-09 15:54 UTC, P-Rwirangira approved these changes

2024-05-09 15:57 UTC, hozayves requested changes
Hey Leo,

Could you relocate the "checkSizeExistance" and "markProduct" functions from the product controller to either the utils or helpers folder?

2024-05-09 16:09 UTC, A-gent64 reviewed
It's working according to it's purpose

2024-05-10 07:27 UTC, JeanIrad approved these changes

2024-05-10 07:30 UTC, niyontwali approved these changes

2024-05-10 07:33 UTC, hozayves approved these changes

2024-05-10 07:56 UTC, merged