[finishes #187354263]crud operations of items to a cart
atlp-rwanda/e-commerce-mavericcks-bn pull request #62
Opened 2024-05-10 11:16 UTC by gracemugwanezak

## Purpose

Performing crud operations on a user's cart

Describe the changes made in this pull request

- Created a cartController file for defining functionality
- Created a cartRoute file for specifying routes
- Created a cart yaml file for documentation

## Testing Instructions

No tests done

## Related Issues

No issues found

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [x] Code follows the project's coding standards
- [x] Changes are covered by tests
- [x] Documentation is updated (if applicable)
- [x] All tests pass

2024-05-13 11:57 UTC, patrickhag commented on src/controllers/productsController.ts
> +    // }
can you please uncomment these codes?

2024-05-13 12:38 UTC, hozayves requested changes
Hey Grace,
From what I see, I believe this model might lead to duplicate data since customers could end up with multiple rows for their cart items. I suggest creating a column for product IDs as an array and a column for the total price. This way, customers can have a single entry for their cart, simplifying the data

2024-05-13 12:38 UTC, hozayves commented on src/controllers/cartController.ts
> +    if (existingItem) {
Hi Grace,
How do you make sure there's enough of the items you've put in your cart available in stock?

2024-05-13 12:38 UTC, hozayves commented on src/database/migrations/20240510102608-create-user-product.js
Hey Grace,

From what I see, I believe this model might lead to duplicate data since customers could end up with multiple rows for their cart items. I suggest creating a column for product IDs as an array and a column for the total price. This way, customers can have a single entry for their cart, simplifying the data

2024-05-13 12:43 UTC, hozayves requested changes
Hi Grace,
How do you make sure there's enough of the items you've put in your cart available in stock? #cartController

2024-05-15 10:44 UTC, JeanIrad requested changes
Please refactor your codes accordingly by removing all those languages that are triggering github action

2024-05-15 10:44 UTC, JeanIrad commented on src/controllers/cartController.ts
> +        message: req.t('requiredFieldsMissing', {
seems you committed the other language John uses in his code use this :
`message: ` the following fields are required: ${missingFields.join(', ')}``

2024-05-20 08:03 UTC, amin-leon approved these changes

2024-05-20 08:03 UTC, amin-leon commented on src/controllers/cartController.ts
> +    const { productId, quantity } = req.body;
why can't you pass productId as a parameter?

2024-05-20 08:03 UTC, amin-leon commented on src/controllers/cartController.ts
> +    const { productId, quantity } = req.body;
pass it as parameter(productId)

2024-05-20 08:03 UTC, amin-leon commented on src/controllers/cartController.ts
> +    const cartItem = await UserProduct.findOne({ where: { userId, productId }, include: { model: Product } });
we have to get also data from Size model.

2024-05-20 11:27 UTC, closed without merging