[Finishes 187354273] password update prompt and password expiration t…
atlp-rwanda/e-commerce-mavericcks-bn pull request #63
Opened 2024-05-11 22:00 UTC by hatfelicien

## Purpose

The purpose of this pull request is to implement the password update prompt feature as described in the provided task. This feature ensures that users are prompted to update their passwords periodically for security purposes.

## Changes Made

.Implemented a password update prompt feature.
.Added functionality to record the last time a password was reset in the user profile model.
.Used Cron jobs to iterate through all users and check if the password expiration has been reached.
.Implemented Node events to handle the password update event.
.Added an environment variable to contain the time for password expiration.

## Testing Instructions
Ensure that the password update prompt is triggered correctly when the expiration time is reached.
Verify that the last time password reset is recorded in the user profile model.
Test the scenarios described in the acceptance criteria, including the restart of the timer for the next update and the enforcement of the password update prompt when ignored.
Validate that node schedule are functioning correctly to iterate through users and check password expiration.
Ensure that Node events are properly handling the password update event.
Test with different expiration times to ensure flexibility and accuracy.
Provide instructions on how to test the changes

## Related Issues
no related issue

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [x] Code follows the project's coding standards

2024-05-12 06:59 UTC, amin-leon requested changes
You can reuse sendMail in helpers instead of duplicating codes in your sendPrompt.ts file. we have setted the way to send a specific email for any case.

2024-05-12 07:14 UTC, amin-leon commented on src/scheduler/index.ts
> +          console.error('lastPasswordUpdated is undefined for user:', user);
use defined logger instead of console

2024-05-12 07:14 UTC, amin-leon commented on src/scheduler/index.ts
> +      console.error('Error scheduling password update prompts:', error);
use defined logger here too

2024-05-12 07:14 UTC, amin-leon commented on src/scheduler/index.ts
> +    console.error('PASSWORD_EXPIRATION_MINUTES environment variable is not defined.');
use defined logger instead of console

2024-05-13 14:45 UTC, hozayves requested changes
Hello sir,
I believe there might be existing functions available for sending emails. Explore how you can utilize these instead of creating your own.

2024-05-13 14:45 UTC, hozayves commented on src/helpers/sendPrompt.ts
> +export const sendPrompt = async (data: IData) => {
Hello sir,

I believe there might be existing functions available for sending emails. Explore how you can utilize these instead of creating your own.

2024-05-13 15:03 UTC, amin-leon approved these changes

2024-05-13 15:03 UTC, amin-leon commented on src/helpers/sendPrompt.ts
> +export const sendPrompt = async (data: IData) => {
yabakoze!  approve

2024-05-13 15:14 UTC, hozayves approved these changes

2024-05-15 07:26 UTC, niyontwali approved these changes

2024-05-15 07:26 UTC, niyontwali commented on package.json
> +    "node-schedule": "^2.1.1",
Well done

2024-05-15 16:36 UTC, merged