Fit bug fix notifications
atlp-rwanda/e-commerce-mavericcks-bn pull request #88
Opened 2024-07-01 14:58 UTC by Favor-star

## Purpose

This pull request is intended to increase the hooks to manage notifications for products's lifecycle in Maveericks e-commerce
## Changes Made

In `productsController` , we added more hooks to manage product's lifecycle and handles all notifications related to it.

## Testing Instructions

No tests needed for this

## Related Issues

No issues yet

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [x] Code follows the project's coding standards
- [x] Changes are covered by tests
- [x] Documentation is updated (if applicable)
- [x] All tests pass

2024-07-09 21:39 UTC, patrickhag approved these changes
LGTM

2024-07-10 08:39 UTC, princenzmw approved these changes
Well done!

2024-07-10 08:48 UTC, niyontwali requested changes

2024-07-10 08:48 UTC, niyontwali commented on src/controllers/notificationsController.ts
> +    console.log(allNotifications);
remove the console please

2024-07-10 12:00 UTC, niyontwali approved these changes

2024-07-10 12:00 UTC, merged